version: '3.8'

services:
  app:
    image: baza-2-frontend
    build:
      context: ./
      target: production
      dockerfile: dockerfile
    restart: always
    ports:
      - '${LOCAL_PORT}:${PORT}'
