version: '3.8'

services:
  app:
    image: baza-2-frontend
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
