export const items = [
  {
    title: "item_1.title",
    text: "item_1.text",
    img: "/images/structure/logoblack.svg",
    width: "120px",
    height: "120px",
    url: "/",
  },
  {
    title: "item_2.title",
    text: "item_2.text",
    img: "/images/structure/skill.svg",
    width: "296px",
    height: "74px",
    url: "https://baza-skill.com.ua",
    openInNewTab: true,
  },
  {
    title: "item_3.title",
    text: "item_3.text",
    img: "/images/structure/educate.svg",
    width: "300px",
    height: "157px",
    url: "/error",
    openInNewTab: true,
  },
  {
    title: "item_4.title",
    text: "item_4.text",
    img: "/images/structure/logoblack.svg",
    width: "120px",
    height: "120px",
    url: "/error",
    openInNewTab: true,
  },
];
